language: cpp
matrix:
  include:
  - compiler: gcc48
    dist: trusty
    sudo: false
    env:
    - COMPILER=g++
    - STD=c++11
  - compiler: gcc49
    dist: trusty
    sudo: false
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.9
    env:
    - COMPILER=g++-4.9
    - STD=c++1y
  - compiler: gcc5
    dist: trusty
    sudo: false
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
    env:
    - COMPILER=g++-5
    - STD=c++1z
  - compiler: gcc6
    dist: trusty
    sudo: false
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
    env:
    - COMPILER=g++-6
    - STD=c++1z
  - compiler: clang35
    dist: trusty
    sudo: false
    env:
    - COMPILER=clang++
    - STD=c++11
  - compiler: clang36
    dist: trusty
    sudo: false
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-3.6
        packages:
        - clang-3.6
    env:
    - COMPILER=clang++-3.6
    - STD=c++11
  # Looks like Clang 3.7 is not available on Trusty right now... not sure why
#  - compiler: clang37
#    dist: trusty
#    sudo: false
#    addons:
#      apt:
#        sources:
#        - ubuntu-toolchain-r-test
#        - llvm-toolchain-trusty-3.7
#        packages:
#        - clang-3.7
#    env:
#    - COMPILER=clang++-3.7
#    - STD=c++11
  - compiler: clang38
    dist: trusty
    sudo: false
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-3.8
        packages:
        - clang-3.8
    env:
    - COMPILER=clang++-3.8
    - STD=c++11
  - compiler: clang39
    dist: trusty
    sudo: false
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-3.9
        packages:
        - clang-3.9
    env:
    - COMPILER=clang++-3.9
    - STD=c++11
  - compiler: clang40
    dist: trusty
    sudo: false
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-4.0
        packages:
        - clang-4.0
    env:
    - COMPILER=clang++-4.0
    - STD=c++1z
  # Clang 5.0 is documented as working in Travis' doc, but in practice it cannot be installed right now
#  - compiler: clang50
#    dist: trusty
#    sudo: false
#    addons:
#      apt:
#        sources:
#        - llvm-toolchain-trusty-5.0
#        packages:
#        - clang-5.0
#    env:
#    - COMPILER=clang++-5.0
#    - STD=c++1z
script:
- $COMPILER --version
- make CXX=$COMPILER STD=$STD
- ./all_tests.out
