image: Visual Studio 2015
platform:
  - x64
  - Win32
configuration:
  - Debug
  - Release
build:
  project: vc12.sln
test_script:
  - ps: Invoke-Expression ".\bin\vc12\$env:PLATFORM\$env:CONFIGURATION\test.exe"
