image: Visual Studio 2017
platform:
  - x64
  - x86
configuration:
  - Debug
  - Release
build:
  project: vc15.sln
test_script:
  - ps: Invoke-Expression ".\bin\vc15\$env:PLATFORM\$env:CONFIGURATION\test.exe"
